In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
a=np.random.rand(8,4) #rand-range is between 0 and 1
print(a)


[[0.60422671 0.38218569 0.15201011 0.95138392]
 [0.44658168 0.35873231 0.38447677 0.87641464]
 [0.36412417 0.33017025 0.78691556 0.97877697]
 [0.09662264 0.18878606 0.99989404 0.46073498]
 [0.19156501 0.11118194 0.27974894 0.91455293]
 [0.29252859 0.22568835 0.92755114 0.89391973]
 [0.62340526 0.59937281 0.80347125 0.10401483]
 [0.24234481 0.40101197 0.57006938 0.09375786]]


In [ ]:
a=10*np.random.rand(8,4) #rand-range is between 0 and 1
print(a)

[[6.3238719  9.85706105 3.48055044 7.04031019]
 [0.15647445 7.00118268 6.48690599 5.40330869]
 [8.26990402 7.45848198 4.04858159 2.80214692]
 [3.08216772 7.46348787 8.45215174 4.9755917 ]
 [3.92758687 7.9500825  4.31577682 2.99279577]
 [1.13098602 6.3795497  1.34922735 6.941973  ]
 [9.98651068 5.09320563 1.08622568 9.0142168 ]
 [4.58190537 6.68534527 7.80583634 7.30071941]]


In [ ]:
a=np.floor(10*np.random.rand(8,4)) #rand-range is between 0 and 1
print(a)

[[7. 0. 4. 3.]
 [0. 7. 2. 9.]
 [5. 2. 0. 3.]
 [9. 6. 0. 7.]
 [7. 5. 6. 1.]
 [7. 4. 0. 6.]
 [0. 6. 2. 3.]
 [3. 7. 6. 8.]]


In [ ]:
b=np.arange(1,33).reshape(8,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
     print(np.vsplit(b,4))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
 print(np.vsplit(b,2))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
np.vsplit(b,(2,5,)) #split it after 2 row aand after 5th row

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
print(np.hsplit(b,(4)))

[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21],
       [25],
       [29]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22],
       [26],
       [30]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23],
       [27],
       [31]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24],
       [28],
       [32]])]


In [ ]:
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,(2,4))


[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32]])]

In [ ]:
np.hsplit(B,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A) #Covert from radius to degree

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(A)

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
P=np.array([21,45,67,89,34,54])
print(np.mean(P))

51.666666666666664


In [ ]:
P=np.array([21,45,67,89,34,54])


In [ ]:
  1np.median(P)

49.5

In [ ]:
np.std(P)

22.10329286680054

In [ ]:
np.var(P)

488.5555555555556

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=10*np.random.rand(24).reshape(6,4)
print(C)

[[6.65793358 7.67301004 0.15179512 9.38975165]
 [1.50506992 5.74605707 6.84358228 0.93703618]
 [3.17530126 5.1802459  1.91357267 9.99531319]
 [6.77123306 0.5822549  3.45484329 7.58074875]
 [1.31807218 5.00815708 8.76377285 9.37261313]
 [4.0782794  2.82702576 2.36869542 7.92606141]]


In [ ]:
print(np.argmax(C))

11


In [ ]:
print(np.argmax(C,axis=1))

[3 2 3 3 3 3]


In [ ]:
print(np.argmax(C,axis=0))

[3 0 4 2]


In [ ]:
print(np.argmin(C))

2




```
# This is formatted as code
```

Search The Indexes

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [ ]:
b=np.array([24,16,7,17,54,60])
for i in b:
  if(i%6==0):
    print(i)

24
54
60


In [ ]:
c=np.array(["banana","cherry","apple"])
print(np.sort(c))

['apple' 'banana' 'cherry']


In [ ]:
c=np.array([True,False,True])
print(np.sort(c))

[False  True  True]


In [ ]:
c=np.array([[3,2,4],[5,0,1]])
print(np.sort(c))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

Iterating through arrays

In [ ]:
names=np.array(["Pavan","Anil","Harsha",])
initials=np.array(["A","K","P"])
for i,j in zip(initials,names):
  print(i,":",j)

A : Pavan
K : Anil
P : Harsha


In [ ]:
a=np.array([10,20,30,35,45,55])
b=np.array([5,6,7,8,9,21])
n=np.multiply(a,b)
print(n)

[  50  120  210  280  405 1155]


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([2,4,6,8,10,12])
n=np.divide(a,b)
print(n)

[5. 5. 5. 5. 5. 5.]


Logarithms

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
print(np.log10(a))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
a=np.array([1,1,2,3,4])
print(np.log(a))

[0.         0.         0.69314718 1.09861229 1.38629436]


Other Mathematical Functions

In [ ]:
a2=np.array([5,6,7,10])
x=np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
a=np.array([10,15,25,15])
x=np.diff(a)
print(x)

[  5  10 -10]


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a)  #takes multiple inputs gives single output
print(gc)

3
